### ISSUE TITLE
Fails to build with Xcode 9 on macOS 10.13

### ISSUE THREAD

**Issue by fxcoudert** [halo/macosvpn#35]
```
** BUILD FAILED **
The following build commands failed:
	CompileC build/macosvpn.build/Release/macosvpn.build/Objects-normal/x86_64/DDOSLogger.o macosvpn/Vendor/CocoaLumberjack/DDOSLogger.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Full logs there: https://gist.github.com/4dd9dd05a6147e9608c1ea548379e365

```
/tmp/macosvpn-20170924-40656-41s3ia/macosvpn-0.3.2/macosvpn/Vendor/CocoaLumberjack/DDOSLogger.m:58:17: error: static_assert failed "format argument mus
t be a string constant"
                os_log_error(OS_LOG_DEFAULT, msg);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'os' imported from /tmp/macosvpn-20170924-40656-41s3ia/macosvpn-0.3.2/macosvpn/Vendor/CocoaLumberjack/DDOSLogger.m:17:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/os/log.h:319:9: note: expanded from mac
ro 'os_log_error'
        os_log_with_type(log, OS_LOG_TYPE_ERROR, format, ##__VA_ARGS__)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/os/log.h:475:5: note: expanded from mac
ro 'os_log_with_type'
    _Static_assert(__builtin_constant_p(format), "format argument must be a string constant"); \
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/macosvpn-20170924-40656-41s3ia/macosvpn-0.3.2/macosvpn/Vendor/CocoaLumberjack/DDOSLogger.m:62:17: error: static_assert failed "format argument mus
t be a string constant"
                os_log_info(OS_LOG_DEFAULT, msg);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'os' imported from /tmp/macosvpn-20170924-40656-41s3ia/macosvpn-0.3.2/macosvpn/Vendor/CocoaLumberjack/DDOSLogger.m:17:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/os/log.h:247:9: note: expanded from mac
ro 'os_log_info'
        os_log_with_type(log, OS_LOG_TYPE_INFO, format, ##__VA_ARGS__)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/os/log.h:475:5: note: expanded from mac
ro 'os_log_with_type'
    _Static_assert(__builtin_constant_p(format), "format argument must be a string constant"); \
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/macosvpn-20170924-40656-41s3ia/macosvpn-0.3.2/macosvpn/Vendor/CocoaLumberjack/DDOSLogger.m:67:17: error: static_assert failed "format argument mus
t be a string constant"
                os_log_debug(OS_LOG_DEFAULT, msg);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'os' imported from /tmp/macosvpn-20170924-40656-41s3ia/macosvpn-0.3.2/macosvpn/Vendor/CocoaLumberjack/DDOSLogger.m:17:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/os/log.h:277:9: note: expanded from mac
ro 'os_log_debug'
        os_log_with_type(log, OS_LOG_TYPE_DEBUG, format, ##__VA_ARGS__)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/os/log.h:475:5: note: expanded from macro 'os_log_with_type'
    _Static_assert(__builtin_constant_p(format), "format argument must be a string constant"); \
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
```

**Comment by halo** [comment]
Hi! Sorry for getting back at you so late. The reason is that I thought the email notification of this issue was created by some continuous integration bot to tell me that High Sierra is failing. I didn't realize it was an actual human being asking me to fix it :D 

Which I think I did. The tests are passing locally, I'm still waiting [for Travis](https://travis-ci.org/halo/macosvpn/builds/281378887) and am going to tag this release `0.3.3` as soon as I know for sure that it works.

**Comment by halo** [comment]
@fxcoudert Travis passing. Please give this release a try if you have High Sierra already: https://github.com/halo/macosvpn/releases/tag/0.3.3

**Comment by fxcoudert** [comment]
@halo it builds fine, on all macOS versions (10.11 and later). Right now, the version is marked as "pre-release", and so we can't update to it just yet. Can you make it an official release?

**Comment by halo** [comment]
Said and done.

Thank you indeed for your help.
